### ISSUE TITLE
TODO from README

### ISSUE THREAD

**Issue by arbakker** [GeodetischeInfrastructuur/coordinate-transformation-api#31]
The actions that need to be executed are primarily based on the recommandations
of the [OGC API Common](./OGC-API-Common.md) spec and the [NL API](./NL-API.md)
Design rues. Examples of these are:

- [x] No trailing slash `../`.
- [x] API-Version header in responses.
- [x] Resource limits on:
  - ~~max size attr~~
  - ~~max features~~
  - ~~max coordinates~~
  - [x] max runtime (30s - configurable)
  - [x] max size request body (2MB - configurable)
- [x]  Additional error messages (implemented with logging and ErrorDetail JSON in HTTP response)
- [x] Changelog publishing on github.com/GeodetischeInfrastuctuur (use github autogenerated changelogs with PRs)
- [x] Allow with POST operatie the crs in the (geo)json, when there is no source-crs  parameter; with additional scenarios for other combinations.

**Comment by arbakker** [comment]
Done.
